#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("zen_collections() works", {

  f <- kwb.pkgstatus:::zen_collections

  kwb.pkgstatus:::zen_collections()

})
