#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:53:16.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("create_report_rpackages() works", {

  f <- kwb.pkgstatus:::create_report_rpackages

  expect_error(
    kwb.pkgstatus:::create_report_rpackages()
    # Argument "secrets_csv" fehlt (ohne Standardwert)
  )

})
