#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("check_docu_dev() works", {

  expect_error(
    kwb.pkgstatus:::check_docu_dev()
    # argument "repo_names" is missing, with no default
  )

})

