#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("check_gitlab_backup() works", {

  expect_error(
    kwb.pkgstatus:::check_gitlab_backup()
    # lexical error: invalid char in json text.
#                                        NA
#                      (right here) ------^
# 
  )

})

