#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("process_hitter_response() works", {

  expect_error(
    kwb.pkgstatus:::process_hitter_response()
    # argument "response" is missing, with no default
  )

})

