#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("prepare_status_rpackages() works", {

  expect_error(
    kwb.pkgstatus:::prepare_status_rpackages()
    # argument "secrets_csv" is missing, with no default
  )

})

