#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_gitlab_repos() works", {

  expect_error(
    kwb.pkgstatus:::get_gitlab_repos()
    # lexical error: invalid char in json text.
#                                        NA
#                      (right here) ------^
# 
  )

})

