#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("url_success() works", {

  expect_error(
    kwb.pkgstatus:::url_success()
    # argument "url" is missing, with no default
  )

})

