#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("badge_travis() works", {

  expect_error(
    kwb.pkgstatus:::badge_travis()
    # argument "repo_full_names" is missing, with no default
  )

})

