#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("badge_gitlab() works", {

  expect_error(
    kwb.pkgstatus:::badge_gitlab()
    # argument "url" is missing, with no default
  )

})

