#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_github_repos() works", {

  f <- kwb.pkgstatus:::get_github_repos

  kwb.pkgstatus:::get_github_repos()

})
