#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_coverages() works", {

  expect_error(
    kwb.pkgstatus:::get_coverages()
    # argument "repo_full_names" is missing, with no default
  )

})

