#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:32.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_gitlab_backup() works", {

  f <- kwb.pkgstatus:::check_gitlab_backup

  kwb.pkgstatus:::check_gitlab_backup()

})
