#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("badge_cran() works", {

  expect_error(
    kwb.pkgstatus:::badge_cran()
    # argument "repo_names" is missing, with no default
  )

})

