#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:30.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("badge_zenodo() works", {

  f <- kwb.pkgstatus:::badge_zenodo

  expect_error(
    kwb.pkgstatus:::badge_zenodo()
    # Argument "repo_full_names" fehlt (ohne Standardwert)
  )

})
