#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:33.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_coverages() works", {

  f <- kwb.pkgstatus:::get_coverages

  expect_error(
    kwb.pkgstatus:::get_coverages()
    # Argument "repo_full_names" fehlt (ohne Standardwert)
  )

})
