#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("create_report_rpackages() works", {

  expect_error(
    kwb.pkgstatus:::create_report_rpackages()
    # argument "secrets_csv" is missing, with no default
  )

})

