#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("get_coverage() works", {

  expect_error(
    kwb.pkgstatus:::get_coverage()
    # argument "repo_full_name" is missing, with no default
  )

})

