#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-24 09:21:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("process_hitter_response() works", {

  f <- kwb.pkgstatus:::process_hitter_response

  expect_error(
    kwb.pkgstatus:::process_hitter_response()
    # Argument "response" fehlt (ohne Standardwert)
  )

})
